### ISSUE TITLE
Just some kudos 👏🏻 

### ISSUE THREAD

**Issue by phil-monroe** [zkuzmic/which-jspm#1]
Hey @zkuzmic - I saw this repo pop up in my Github feed and it made me smile. I can totally relate to the problem you are solving...

![giphy](https://user-images.githubusercontent.com/723421/190705624-7ffae94e-70f0-40ac-bd4b-4c461a885ce7.gif)

Hope you are doing well and congrats on the new job at Indeed! 🎉

**Comment by zkuzmic** [comment]
Hey thanks, Phil! Hope you've been well!
